services:
  postgres:
    container_name: store-mag-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - store-common-network

volumes:
  postgres:

networks:
  store-common-network:
    driver: bridge
    name: store-common-network
